name: test

on: push

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
  HUSKY: 0 # Bypass husky commit hook for CI

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14', '16', '17']
    name: Install, build, and test (Node ${{ matrix.node }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Cache pnpm modules'
        uses: actions/cache@v2
        with:
          path: ${{ env.PNPM_CACHE_FOLDER }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: 'Install pnpm 6'
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.x

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: 'Configure pnpm'
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install
        run: pnpm --frozen-lockfile install

      - name: Test
        run: pnpm run test
